# BEGIN_KITTY_THEME
# Sakura Night
include current-theme.conf
# END_KITTY_THEME

confirm_os_window_close 0

#FONTS
font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Extra Bold
bold_italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic

font_size 15

#TRANSPARENCY
background_opacity 0.65

#LAYOUT
enable_layout tall,*

#WINDOWS
window_margin_width 4
window_border_width 2pt
single_windoww_margin_width 0
#BACKGROUND
# background_image ~/wallpaper/anime.png
# background_image_layout clamped

# background_tint 0.10
# background_tint_gaps -10

#TABS 
# tab_bar_style 
# tab_powerline_style slanted 
tab_activity_symbol $


#MAP KEYS
map F1 new_window_width_cwd

