#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/
# --- NVIDIA FIX ---
env = WLR_NO_HARDWARE_CURSORS,1
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND=direct

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

general {
    gaps_in = 4
    gaps_out = 5 15 15 15
    border_size = 4

    col.active_border = rgba(ff2f92ff)   
    col.inactive_border = rgba(5c2a3faa)

    resize_on_border = false
    allow_tearing = false
    layout = master

    allow_tearing = true
}

decoration {
    rounding = 12
    rounding_power = 10

    active_opacity = 1.0
    inactive_opacity = 0.95

    shadow {
        enabled = true
        range = 2
        render_power = 4
        color = rgba(ff2f9288)
    }

    blur {
        enabled = true
        size = 3
        passes = 2
        vibrancy = 0.18
    }
}

