
#  $$$$$$\
# $$  __$$\
# $$ /  \__| $$$$$$\  $$\   $$\  $$$$$$\   $$$$$$$\  $$$$$$\
# \$$$$$$\  $$  __$$\ $$ |  $$ |$$  __$$\ $$  _____|$$  __$$\
#  \____$$\ $$ /  $$ |$$ |  $$ |$$ |  \__|$$ /      $$$$$$$$ |
# $$\   $$ |$$ |  $$ |$$ |  $$ |$$ |      $$ |      $$   ____|
# \$$$$$$  |\$$$$$$  |\$$$$$$  |$$ |      \$$$$$$$\ \$$$$$$$\
#  \______/  \______/  \______/ \__|       \_______| \_______|



source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/archdope.conf
source = ~/.config/hypr/animation.conf
source = ~/.config/hypr/layout.conf